name: RUN test CI/CD actions

on: [push]

jobs:
  Daily-Run-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip3 install -r requeirements.txt

      - name: Run python script
        run: python3 app.py
